### ISSUE TITLE
add S3 objects for generated data

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/db.rnacentral#21]
They should be inside a `data` object.

**Comment by laughedelic** [comment]
Which generated data? In this bundle we only mirror RNAcentral and the destination in S3 are in the code already.

**Comment by eparejatobes** [comment]
Sorry missed this https://github.com/ohnosequences/db.rnacentral/blob/6777d63115e208fa02cdd8c906fc88b2a6d53d5d/src/main/scala/rnacentral.scala#L33-L34
