### ISSUE TITLE
RNAcentral v8

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/db.rnacentral#33]
https://github.com/RNAcentral/rnacentral-import-pipeline/pull/12 got merged recently.

**Comment by AntonPetrov** [comment]
Hi there! 

Just wanted to let you know that RNAcentral 8 is now live! 🎉 ✨  

Here is a breakdown of the new features and data:
http://blog.rnacentral.org/2017/12/rnacentral-release-8.html

Feel free to get in touch if you have any questions. We would love to learn about how you use RNAcentral and if there is anything we can do to help. Thanks!

**Comment by laughedelic** [comment]
Thanks @AntonPetrov! Congratulations with the new release! 🎉 

In short, we use RNAcentral data to build a reference DB: [db.rna16s](https://github.com/ohnosequences/db.rna16s) for metagenomics analysis with our [MG7](https://github.com/ohnosequences/mg7) pipeline. But I think it's better if somebody else from our bioinformatics team talks about it with you.

/cc @ohnosequences/bioinformatics

**Comment by AntonPetrov** [comment]
Thank you @laughedelic! The MG7 pipeline looks great. Feel free to get in touch if RNAcentral can do anything to help.

**Comment by rtobes** [comment]
@AntonPetrov, 
Thanks for your comments and congratulations for your new release 8. 
After reviewing many different open databases we selected RNAcentral as the best resource for building a sufficiently precise and complete 16S database. We have designed an algorithm for automated refinement that, starting from the 16S sequences from each new RNAcentral release, is able to build a non redundant database with consistent and coherent assignments for all the 16S sequences included in it.
All this work has been done by **Ohnosequences!** team.  **Ohnosequences!** is the Research group of the company Era7 Bioinformatics. The team is interdisciplinary and contributes with databases and bioinformatics tools to the scientific community within an open source model. I have the luck of leading the **Ohnosequences!** research team. The main founders of this group are @eparejatobes which has been the leader of the design and software development of this 16S database and of the MG7 tool, @marina-manrique and @epareja (CEO of Era7 Bioinformatics). @laughedelic is now forming part of ohnosequences! group and as he has told you we use our refined 16S database as reference database for our taxonomic assignment MG7 tool. We are also building other new databases also based on RNAcentral releases for ITS and for 18S sequences using a similar strategy.

Ask us any additional information that you need

**Comment by AntonPetrov** [comment]
Thank you for the detailed information @rtobes! 

Our goal for 2018 is to annotate all sequences with Sequence Ontology terms, which could make it easier for you to selectively retrieve different types of rRNA, such as 16S, 18S etc. If you can think of any other improvements that would be helpful for you, just let me know.
