### ISSUE TITLE
Merge api.rnacentral

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/db.rnacentral#42]
See ohnosequences/api.rnacentral#13.

**Comment by eparejatobes** [comment]
Needs #40 and #40.

**Comment by agarciamontoro** [comment]
The code from `api.rnacentral` is already here. Actually, both repositories are nearly the same. I think we should close this issue and archive `api.rnacentral`. Am I missing something else here, @eparejatobes? I want to finish this asap.

**Comment by agarciamontoro** [comment]
I double-checked with @eparejatobes and we both know it is safe to close this issue and archive `api.rnacentral`.
