### ISSUE TITLE
 Update to RNACentral v10

### ISSUE THREAD

**Issue by agarciamontoro** [ohnosequences/db.rnacentral#44]
New version, yay!

https://blog.rnacentral.org/2018/08/rnacentral-release-10.html

**Comment by agarciamontoro** [comment]
I just noticed that there is a new type of RNA that we currently cannot parse: 

```
bidirectional_promoter_lncrna
```

I don't really know what this is, but for the moment I just added it to [the list of RNA types](https://github.com/ohnosequences/db.rnacentral/blob/master/src/main/scala/types.scala#L44-L72) we can manage.

Just writing it here so you know (cc @rtobes @eparejatobes)

**Comment by rtobes** [comment]
@agarciamontoro,

GTK, Thanks!

Bidirectional promoters are promoters that can act as promoters for two genes adjacent and divergently oriented: <--gene1--- promoter ---gene2-->. This kind of promoters can be read in the 2 orientations:
<--gene1---    <--promoter---
---promoter-->   ---gene2-->      

> Bidirectional promoters are short (<1 kbp) intergenic regions of DNA between the 5' ends of the genes in a bidirectional gene pair. A “bidirectional gene pair” refers to two adjacent genes coded on opposite strands, with their 5' ends oriented toward one another. The two genes are often functionally related, and modification of their shared promoter region allows them to be co-regulated and thus co-expressed. Bidirectional promoters are a common feature of mammalian genomes. About 11% of human genes are bidirectionally paired.

_Taken from wikipedia_

**Comment by agarciamontoro** [comment]
Closed with release [v0.13.0](https://github.com/ohnosequences/db.rnacentral/releases/tag/v0.13.0).
