### ISSUE TITLE
The ID mappings and the sequences are no longer sorted

### ISSUE THREAD

**Issue by agarciamontoro** [ohnosequences/db.rnacentral#45]
Up to version 7.0 of RNACentral, we could assume that the files `id_mapping.tsv` and `rnacentral_species_specific_ids.fasta` contained the entries in the same order (the mapping had several lines per entry, but always grouped). This made possible to iterate both files at the same time to compare their info: in [entries.scala#L8](https://github.com/ohnosequences/db.rnacentral/blob/master/src/main/scala/entries.scala#L8) we did the following, which basically yields pairs of (sequence, id mapping), iterating the files in order:

```scala
(sequences parseFrom data) zip (IDMapping entryAnnotationsByRNAIDOrErrors data)
```

But from the 8th release of RNACentral, the fasta sequences are not ordered (it seems the mappings are still ordered by their ID), so a simple zip between the iterators of sequences and the ID mappings is not enough.

We need to iterate the sequences and look for that specific RNA ID in the ID mappings, so we can retrieve the annotations information.

**Comment by eparejatobes** [comment]
I think we should leave the FASTA file as-is (quite big, sorting it could require a considerable amount of RAM) and store ID mappings in a map `RNACentralID -> Array[Annotation]` or whatever the names are (assuming the ID mapping file is sorted by ID)
